services:
  - type: web
    name: rr-steels
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mongodb
      - key: APP_KEY
        fromParam: appKey
      - key: MONGODB_URI
        fromParam: mongodbUri
      - key: MONGODB_DATABASE
        value: steel_retail

parameters:
  - key: appKey
    description: Laravel Application Key (base64:...)
    required: true
  - key: mongodbUri
    description: MongoDB Atlas Connection String
    required: true
